### ISSUE TITLE
arc11@1.5.0.31351: decompress error

### ISSUE THREAD

**Issue by B0pol** [tree-s/arc#1]
I can't update arc

scoop update * -k
arc11: 1.2.1.29300 -> 1.5.0.31351
Updating one outdated app:
Updating 'arc11' (1.2.1.29300 -> 1.5.0.31351)
Downloading new version
Loading Arc.x64.msix from cache
Checking hash of Arc.x64.msix ... ok.
Loading Microsoft.WindowsAppRuntime.1.5.5001.119.156.0.msix from cache
Checking hash of Microsoft.WindowsAppRuntime.1.5.5001.119.156.0.msix ... ok.
Loading Microsoft.VCLibs.x64.14.00.Desktop.14.0.30704.0.appx from cache
Checking hash of Microsoft.VCLibs.x64.14.00.Desktop.14.0.30704.0.appx ... ok.
Uninstalling 'arc11' (1.2.1.29300)
Installing 'arc11' (1.5.0.31351) [64bit] from 'arc' bucket
WARN  Cache is being ignored.
Arc.x64.msix (254,3 MB) [=====================================================================================] 100%
Microsoft.WindowsAppRuntime.1.5.5001.119.156.0.msix (21,5 MB) [===============================================] 100%
Microsoft.VCLibs.x64.14.00.Desktop.14.0.30704.0.appx (6,3 MB) [===============================================] 100%
Extracting dl.7z ... done.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\user\scoop\apps\arc11\1.5.0.31351\dl.7z.
Log file:
  ~\scoop\apps\arc11\1.5.0.31351\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/tree-s/arc/issues/new?title=arc11%401.5.0.31351%3a+decompress+error

Log file:
7-Zip 24.06 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-05-26

Scanning the drive for archives:

ERROR: File not found.
C:\Users\user\scoop\apps\arc11\1.5.0.31351\dl.7z

System ERROR:
File not found

it is indeed not in this folder

**Comment by tree-s** [comment]
Thanks for giving this a go. It's very much a work in progress.  I can fix the above issue, but even then there are specific block(s)/checks to prevent the application from being run without using the actual windows installer.

My current thinking is that there is a registry check performed by the application that I need to also account for for the scoop install.

Cheers and thanks for your patience!

**Comment by tree-s** [comment]
So I fixed your issue and will be closing this ticket, but you might not get that much further due to the issue I mentioned above.

**Comment by B0pol** [comment]
i can confirm it worked, I successfully installed version 1.6.1.32587
